ASP_WS/Controllers/BreedController.cs
using Microsoft.AspNetCore.Mvc;
using ASP_WS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ASP_WS.Controllers
{
    public class BreedController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        AppDbContext _appDbContext;

        public BreedController(ILogger<HomeController> logger, AppDbContext context)
        {
            _logger = logger;
            _appDbContext = context;
        }

        public IActionResult Page(int id)
        {
            return View(_appDbContext.Breeds.First(u => u.Id == id));
        }
        #region Breed
        public IActionResult CreateBreed()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateBreed(Breed breed)
        {
            _appDbContext.Breeds.Add(breed);
            await _appDbContext.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Edit(int id)
        {
            Breed breed = _appDbContext.Breeds.First(u => u.Id == id);
            return View(breed);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Breed breed, int id)
        {
            Breed oldBreed = _appDbContext.Breeds.First(u => u.Id == id);
            oldBreed.Description = breed.Description;
            oldBreed.Name = breed.Name;
            await _appDbContext.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }


        #endregion


    }
}

ASP_WS/Controllers/DogController.cs
using Microsoft.AspNetCore.Mvc;
using ASP_WS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ASP_WS.Controllers
{
    public class DogController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        AppDbContext _appDbContext;
        IWebHostEnvironment _appEnvironment;

        public DogController(ILogger<HomeController> logger, AppDbContext context, IWebHostEnvironment appEnvironment)
        {
            _logger = logger;
            _appDbContext = context;
            _appEnvironment = appEnvironment;
        }

        #region Dog

        public IActionResult CreateDog()
        {
            var Owners = _appDbContext.Owners.ToList();
            var Breeds = _appDbContext.Breeds.ToList();
            ViewBag.Owners = new SelectList(Owners, "Id", "Name");
            ViewBag.Breeds = new SelectList(Breeds, "Id", "Name");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateDog(string Name, int BreedId, int OwnerId, DateTime Birthday, IFormFile uploadedfile)
        {
            if (uploadedfile != null)
            {
                // путь к папке Files
                string path = "/Files/" + uploadedfile.FileName;
                // сохраняем файл в папку Files в каталоге wwwroot
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedfile.CopyToAsync(fileStream);
                }
                Dog Dog = new Dog { Name = Name, BreedId = BreedId, OwnerId = OwnerId, Birthday = Birthday, AvatarPath = path };
                _appDbContext.Dogs.Add(Dog);
                await _appDbContext.SaveChangesAsync();
                
            }
            return RedirectToAction("Index", "Home");

        }

        public async Task<IActionResult> Delete(int id)
        {
            _appDbContext.Dogs.Remove(_appDbContext.Dogs.First(u => u.Id == id));
            await _appDbContext.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Edit(int id)
        {
            var Owners = _appDbContext.Owners.ToList();
            var Breeds = _appDbContext.Breeds.ToList();
            ViewBag.Owners = new SelectList(Owners, "Id", "Name");
            ViewBag.Breeds = new SelectList(Breeds, "Id", "Name");
            Dog breed = _appDbContext.Dogs.First(u => u.Id == id);
            return View(breed);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string Name, int BreedId, int OwnerId, DateTime Birthday, IFormFile uploadedfile, int id)
        {

            Dog oldDog = _appDbContext.Dogs.First(u => u.Id == id);
            oldDog.Name = Name;
            oldDog.OwnerId = OwnerId;
            oldDog.BreedId = BreedId;
            oldDog.Birthday = Birthday;
            if (uploadedfile != null)
            {
                // путь к папке Files
                string path = "/Files/" + uploadedfile.FileName;
                // сохраняем файл в папку Files в каталоге wwwroot
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedfile.CopyToAsync(fileStream);
                }
                oldDog.AvatarPath = path;
            }
            await _appDbContext.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }


        #endregion

        public IActionResult Page(int id)
        {
            return View(_appDbContext.Dogs.Include(u => u.Owner).Include(u=> u.Breed).First(u => u.Id == id));
        }
    }
}

ASP_WS/Controllers/OwnerController.cs
using Microsoft.AspNetCore.Mvc;
using ASP_WS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ASP_WS.Controllers
{
    public class OwnerController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        AppDbContext _appDbContext;

        public OwnerController(ILogger<HomeController> logger, AppDbContext context)
        {
            _logger = logger;
            _appDbContext = context;
        }

        #region Owner

        public IActionResult CreateOwner()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateOwner(Owner owner)
        {
            _appDbContext.Owners.Add(owner);
            await _appDbContext.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Edit(int id)
        {
            Owner owner= _appDbContext.Owners.First(u => u.Id == id);
            return View(owner);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Owner owner, int id)
        {
            Owner oldOwner = _appDbContext.Owners.First(u => u.Id == id);
            oldOwner.Name = owner.Name;
            oldOwner.LastName = owner.LastName;
            await _appDbContext.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        #endregion



        public IActionResult Page(int id)
        {
            
            return View(_appDbContext.Owners.Include(u => u.Dogs).First(u => u.Id == id));
        }
    }
}

ASP_WS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP_WS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASP_WS.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP_WS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Breed" asp-action="CreateBreed">Добавить породу</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dog" asp-action="CreateDog">Добавить собаку</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Owner" asp-action="CreateOwner">Добавить хозяина</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ASP_WS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>